runtime: nodejs20

env_variables:
  PORT: "8080"
  NODE_ENV: "production"
  API_TOKEN: "AIzaSyCOsl1ZiR5Fjnpsl0EB0HFkTa5zBmShmY8"
  FIREBASE_PROJECT_ID: "config-management-d60ee"
  FIREBASE_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClR3Ef5uR1sXQr
    MOSiVW1VOrck6cBCdbWH1Y5ChdRydoEZpX6WbaAeHvLNF+5Tk50+ItFC32GARID1
    /mjuVn/8ap9+f1r4M//7buUIeNkvFN8JUi0enEYCxz0mJ1k8iaYjtk5l4ni4yfQd
    9Bje6TB6+8wrhobbutDylbPdzJKijTr5JtKcPFDryTtr5m9i3tjiSvNN7tafg20t
    b8fhB79cLF3w5CFmqkTpL8TZumM1Y7I9PNM+MUfD0WTdev/X5AAu5sOTnMWdbY4J
    hXjYehhQ3kBra7g3WG4lx1xz/WxUFqcDDAqHDc9x/Ujclo1yL2Y0mXSmNy8FaEFK
    0iOXg4mpAgMBAAECggEAUp8zoGCCfYk/iuXOrY3p8WzAKA5II5EHNceebYfMS4oN
    AH6YGOflXplXBAq+A36r4Odz16umaIIWO6K53sdUBKFiaNCOb7xC73Sgvsr2uxAC
    bPzs/Dvfzby+x0dtVxNyf7C/YTRE6A9g3uZq1mgY6andBzchTE+H63TFrQ96kBId
    /8qw+uqCpzjq5vv9Vo+GSJW2nFpu5u3D8D8ZfTV+ToSThVz9JxMi6gtcjhoGsofa
    XL9/lsGmOUOCgpSQAUngQQn/MHuDcT9+pU/aVEgEFEYCxxlt48NM5YCWTRQVbLI2
    TSNRON30XCzLT8tANa0rbtKWuJ8hl/eTLJ/My/Yi3wKBgQDk4gY+6ODFeKP1WLql
    zoZ1snswrjirkpX0p9ECNJKb+9zMQ8spmbVc4npz1soCFsrIeh1A21LyIK93Wmed
    2hDsovVhbqqEd+oAwsKdldZ7fePZ8PxcSRinSNezegJqjYu5D8Y6nsxzMYUEjWMr
    rOFIfxzzsW8+D9owq9tGrvFPXwKBgQC43FM1ul7re46PLBREvX/Af1TN/SfTT7+H
    dFrRwHQwS/HE1dEEHXRqhfk6Qtt2dZE6lgaPcTWWG5STyVbOPp6ay/siLr1YnC60
    Lh+bsCR7pbbr8v4RMxHkNtJB4GnwZxnPNgL2ytyDrTZ6/s0skr/KQ0Oo+2SSe4+I
    aaY0+IUr9wKBgQC7NE9NdyYY/cKE8sy+vvvlGlV+DJGXa26xS+08s4lSgZ8nhy+N
    WAYp8aecRYq2SLQVYyO4H2tpVOiPY2cqieib0/GFfoGDlZzUgHezcpGaMe6CHIQc
    a0D52i9qwZlmU117wPYujiHE+jTE82uwllcw957Th0XoagjZFEdmOcJvWwKBgBNo
    xq/QdqDg4zHzHdmtz9kFRYEvQFw2dlShiduWClz7zFGvZXe6I/v/PxC37lT8uRfe
    oqey6j5tfOcbb6rN9lcobaDEKYtBMsImSZlOIDZ/SrpxU+24X/uHKgJSrqzYFmSk
    NiF1YTvOFvdJA3/XlJ2G/HakloWuxX48IYBUS583AoGBAN5cV9vFlSm4T6h5ez2K
    T8A98oi7tnlVxmtHCBFbbFvZi9/5MFX0F63aDGXJg1rPXGphrH9OLMWfe0NzzR0B
    OWZF0xcl3Fk9WIWdpSINNAlKbGuFqYNU53NTmI+nNGdpZCvHwOeq6QrOP15Bv3XS
    WBnsP38Dp0ZKBSDzd63mhBoH
    -----END PRIVATE KEY-----
    
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@config-management-d60ee.iam.gserviceaccount.com"
  FIREBASE_STORAGE_BUCKET: "config-management-d60ee.firebasestorage.app"
