runtime: nodejs20

env_variables:
  PORT: {{PORT}}
  NODE_ENV: {{NODE_ENV}}
  API_TOKEN: {{API_TOKEN}}
  FIREBASE_PROJECT_ID: {{FIREBASE_PROJECT_ID}}
  FIREBASE_PRIVATE_KEY: {{FIREBASE_PRIVATE_KEY}}
  FIREBASE_CLIENT_EMAIL: {{FIREBASE_CLIENT_EMAIL}}
  FIREBASE_STORAGE_BUCKET: {{FIREBASE_STORAGE_BUCKET}}
